spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_SERVER_ADDRESS:localhost}:${POSTGRES_DB_SERVER_PORT:5432}/karthikdb
    username: ${POSTGRES_USER:karthik}
    password: ${POSTGRES_PASSWORD:karthikr1234}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      show-sql: true
      format-sql: true
      type: info
      use-sql-comments: true
      properties:
        hibernate.use_sql_comments: true
        hibernate.format_sql: true


management:
  endpoint:
    health:
      show-details: ALWAYS
    endpoints:
      web:
        exposure:
          include: "*"

logging:
  level:
    org.springframework: INFO
    com.farukgenc.boilerplate.springboot: INFO

## FIXME : Customize JWT token and Swagger information for your application

jwt:
  secretKey: secret
  expirationMinute: 10

